_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.10
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.10
            "13": linux-x86_64
